PUT http://localhost:8080/events/2
Content-Type: "application/json"

{
    "name": "Bret",
    "description": "Multi-layered client-server neural-net",
    "location":"harness real-time e-markets",
    "dateTime": "2024-03-20T15:29:00.000Z",
}