POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkthcmxleV9EYWNoQGphc3Blci5jb20iLCJleHAiOjE3MTExMTE3NDksInVzZXJJZCI6Mn0.vMkUmIfVkvl8kST3RN20Ka-zQtojwbOKbVYcvzKH-aA

{
    "name": "Glenna Reichert",
    "description": "Configurable multimedia task-force",
    "location":"A test location",
    "dateTime": "2024-03-22T18:49:00.000Z"
}